# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springbatch_db
      MYSQL_USER: springbatch
      MYSQL_PASSWORD: springbatch
    ports:
      - 3306:3306
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./conf.d/my.cnf:/etc/mysql/conf.d/my.cnf

  adminer:
    image: adminer
    ports:
      - 9080:8080
