CREATE TABLE T_USER (
	USER_ID BIGINT NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(32) NOT NULL,
	FAMILY_NAME VARCHAR(32) NOT NULL,
	AGE INT NOT NULL,
	WORK_STATUS INT NOT NULL,
	UPDATE_DATE DATE
) ENGINE=InnoDB;
